fix: fail if can not locate the path of package.json

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -74,8 +74,8 @@ steps:
     echo Locate package.json for: $(packageName)
     PACKAGEFOLDER=`node findPackage.js $(packageName) $(repoDir)`
     if [[ -z "$PACKAGEFOLDER" ]]; then
-      echo "WARN: no valid package.json found, fallback to $(repoDir)"
-      PACKAGEFOLDER=$(repoDir)
+      echo "Error: ENOENT, error path package.json with name=$(packageName)"
+      exit 1
     fi
     echo PACKAGEFOLDER: $PACKAGEFOLDER
     echo "##vso[task.setvariable variable=packageFolder;]$PACKAGEFOLDER"
